# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_stringer_wrappers", use_symbols = TRUE, package_name = "stringer")

#' @docType package
#' @usage NULL
#' @useDynLib stringer, .registration = TRUE
NULL

str_regex_count <- function(strings, pattern) .Call(wrap__str_regex_count, strings, pattern)

str_text_count <- function(strings, sub) .Call(wrap__str_text_count, strings, sub)

