# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_stringer_wrappers", use_symbols = TRUE, package_name = "stringer")

#' @docType package
#' @usage NULL
#' @useDynLib stringer, .registration = TRUE
NULL

str_regex_count <- function(strings, pattern) .Call(wrap__str_regex_count, strings, pattern)

str_text_count <- function(strings, sub) .Call(wrap__str_text_count, strings, sub)

str_regex_detect <- function(strings, pattern) .Call(wrap__str_regex_detect, strings, pattern)

str_text_detect <- function(strings, sub) .Call(wrap__str_text_detect, strings, sub)

str_regex_extract <- function(strings, pattern) .Call(wrap__str_regex_extract, strings, pattern)

str_text_extract <- function(strings, sub) .Call(wrap__str_text_extract, strings, sub)

single_str_regex_extract_all <- function(string, pattern) .Call(wrap__single_str_regex_extract_all, string, pattern)

single_str_text_extract_all <- function(string, sub) .Call(wrap__single_str_text_extract_all, string, sub)

str_length <- function(str) .Call(wrap__str_length, str)

